### ISSUE TITLE
[CI] `tflint` job is actually `make vet`

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1543]
There is a following job in the `.zuul.yaml`:
```yaml
- job:
    name: tflint
    parent: golang-make
    vars:
      make_command: vet
```

But in the Makefile:
```make
tflint: tools
	./scripts/run-tflint.sh
```
