### ISSUE TITLE
project name/id not working in provider versions 1.22.6 & 1.22.7

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#826]
We are experiencing problems with the two newest versions of the terraform provider (1.22.6 & 1.22.7).  
When running "terraform plan" we get:
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: no project name/id or delegated project is provided

  on provider.tf line 1, in provider "opentelekomcloud":
   1: provider "opentelekomcloud" {

```

But we have the `project_name` defined in our `clouds.yaml` file.

This doesn't happen on the older provider versions <= 1.22.5.

# Terraform Version

Tested on
v0.13.0
v0.14.0

# Affected Resource(s)

global issue of the provider

# Terraform Configuration Files
`provider.tf`
```hcl
provider "opentelekomcloud" {
    cloud = "open-telekom-cloud"
}

```

`versions.tf`
```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    opentelekomcloud = {
      source = "opentelekomcloud/opentelekomcloud"
      version = "1.22.6"
    }
  }
}
```

For 1.22.7, replace `version = "1.22.6"` with `version = "1.22.7"`.

Authentication in `clouds.yaml`
```
clouds:
  open-telekom-cloud:
    region_name: eu-de
    auth:
      project_name: eu-de_my-project
      username: my_user
      user_domain_name: OTC-EU-DE-000000000010000XXXXX
      auth_url: https://iam.eu-de.otc.t-systems.com/v3
```
password is set in `secure.yaml`

# Debug Output/Panic Output

https://gist.github.com/shaderecker/b1123e9a033fcf32bfd66737f200fcff

# Steps to Reproduce

1. `terraform init`
2. `terraform plan`

# Expected Behavior

Project is found and read from `project_name` in `clouds.yaml`

# Actual Behavior

Terraform is unable to find and use the `project_name` set in `clouds.yaml`

# Important Factoids

no

# References

no
